---
title: "Accessing the BuenrostroLab Workstation"
author: Caleb Lareau
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting

Connecting to the BuenrostroLab workstation with a variety of tips and tricks via `ssh`. Throughout the document, I'll use `LOCALUSERNAME` as the username that's on the workstation and `BROADUSERNAME` as your username for the Broad (they may or may not be different in actuality). 

## Easy, obvious way

- Connect to Broad VPN using your username/password (via `Cisco Anyconnect`, log into `vpn.broadinstitute.org`)
- `ssh` into the workstation. 
```
ssh LOCALUSERNAME@10.75.108.34
```

## Accessing RStudio

- As far as I've been able to figure things out, to access RStudio, you have to be connected to the Broad VPN. Once you are connected, type the following in any web browser to access RStudio on the workstation:

```
http://10.75.108.34:8787
```
- What this means is that RStudio server is available through port `8787` at the designated IP address of the workstation. 

## SSH Tunneling
Perhaps we may be interested in accessing the work station without using the VPN. This may be particularly useful if we want to transfer files between servers. To do this, we're going to create an `ssh` tunnel to the workstation through a publically facing Broad server (e.g. `gold.broadinstitute.org`). Here are the basic steps--

- Open two terminal windows. 
- In one terminal window, we're going to expose the workstation server to port `2233` like so--
```
ssh -L 2233:10.75.108.34:22 BROADUSERNAME@gold.broadinstitute.org
```

- After password authentication and two-factor authentication, this terminal window will bridge the wortkstation and the currently used computer through port `2233`. Note: `2233` was a semi-arbitrary choice on my part. You can realistically do any number of ports, but some (e.g. `22` are blocked for specific purposes. Unless you know what you're doing, just stick to `2233`). 
- After setting up the conenction above, minimize this terminal window. It has to be active and running for the subsequent steps to work. 
- Now, we can `ssh` or `scp` to the workstation using this exposed port (and thus without the need to VPN)
- To `ssh`, we have to remove the strict RSA key checking since our login is a dynamic process and point our connection to the exposed port via local host: 
```
ssh -o StrictHostKeyChecking=no -p 2233 LOCALUSERNAME@localhost
```

## Moving Files
- Perhaps we want to `scp` files, such as all the single-cell ATAC `bam` files. This can be done using the form of the following command:
```
scp -o StrictHostKeyChecking=no -P 2233 `find ./ -name "singles*bam"` LOCALUSERNAME@localhost:/home/LOCALUSERNAME/data/
```
An important thing to not here is that the `scp` synatx requires a captial "P" whereas `ssh` uses a lowercase "p" to specify the port.

- Rather than watching all of the files transfer, we may want to throw the command in the background. This way, we can close our windows and do something else. See the discussion [here](https://bharatikunal.wordpress.com/2010/10/20/scp-as-a-background-process/). Thus, the final command that was executed with port `2233` still exposed in another command window was
```
nohup scp -o StrictHostKeyChecking=no -P 2233 `find ./ -name "singles*.st.bam"` LOCALUSERNAME@localhost:/home/LOCALUSERNAME/data/ > nohub.out 2>&1
*ctrl + z*
bg
```
- Note: if you want to `nohup` the file transfer, you'll also have to have the `ssh` connection in the background  as well (with the `-f -N` flags in the first command). 
- Note: If you do this, then read [this](http://stackoverflow.com/questions/9447226/how-to-close-this-ssh-tunnel) discussion on closing out ssh ports. 
- Note: Again, there's nothing special about the port number `2233`. If it's closed when you try to establish the connection in the first execution, you will get notified that the port is closed. Simply replace `2233` with some other port number (e.g. `2244`) that isn't an obvious one (to avoid overlap).

## Important
- You'll want to close the ssh port before exiting whatever server you're on. This isn't a big deal if you ran the port connection in the foreground. However, if you ran it in the background (i.e. the `-f -N` flags), then you'll need to kill the connection to make your server access play friendly in the future. From [the post linked above](http://stackoverflow.com/questions/9447226/how-to-close-this-ssh-tunnel), see which connection is responsible for the port connection:
```
ps aux | grep 2233
```
and then look for the second column that has the `pid`. Say this number is `14651`. Close it off using the following:
```
kill -9 14651
```

## Aliases
- All of these commands can be added to your `.bashrc` file under simple commands that will make your life much, much easier. Ask Caleb if you want to do this/don't know how to do this. For example, we can change the first command that builds the tunnel using the following command:

```
echo tunnel2233="ssh -L 2233:10.75.108.34:22 BROADUSERNAME@gold.broadinstitute.org" >> ~/.bashrc
```
which will allow you to replace the command to tunnel to the server by simply typing `tunnel2233` rather than the long `ssh` command. 
